name: luscii_patient_actions_sdk_platform_interface
description: A common platform interface for the luscii_patient_actions_sdk plugin.
version: 0.7.0+1
repository: https://github.com/Digizorg/luscii_patient_actions_sdk
homepage: https://github.com/Digizorg/luscii_patient_actions_sdk

environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
