name: pub_publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2

      - name: ğŸ“¦ Configure Pub Credentials
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          echo '$CLOUDSMITH_API_KEY' | flutter pub token add https://dart.cloudsmith.io/digizorg/default

      - name: ğŸ“¦ Publish Packages
        run: |
          # Define the package directories in the order they should be published
          packages=(
            "luscii_patient_actions_sdk_platform_interface"
            "luscii_patient_actions_sdk_android"
            "luscii_patient_actions_sdk_ios"
            "luscii_patient_actions_sdk"
          )

          # Loop through packages and publish in order
          for package in "${packages[@]}"; do
            echo "ğŸ“¦ Publishing $package"
            cd "./$package" || exit 1
            flutter pub get
            dart pub publish --dry-run
            dart pub publish --force
            cd .. || exit 1
            echo "âœ… Published $package"
          done
