name: pub_publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2

      - name: ğŸ“¦ Configure Pub Credentials
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          echo '$CLOUDSMITH_API_KEY' | flutter pub token add https://dart.cloudsmith.io/digizorg/default

      - name: ğŸ“¦ Publish Main SDK Package
        working-directory: ./
        run: |
          flutter pub get
          dart pub publish --dry-run
          dart pub publish --force

      - name: ğŸ“¦ Publish Platform Interface Package
        working-directory: ./luscii_patient_actions_sdk_platform_interface
        run: |
          flutter pub get
          dart pub publish --dry-run
          dart pub publish --force

      - name: ğŸ“¦ Publish Android Package
        working-directory: ./luscii_patient_actions_sdk_android
        run: |
          flutter pub get
          dart pub publish --dry-run
          dart pub publish --force

      - name: ğŸ“¦ Publish iOS Package
        working-directory: ./luscii_patient_actions_sdk_ios
        run: |
          flutter pub get
          dart pub publish --dry-run
          dart pub publish --force
